server:
  port: 8080

spring:
  profiles:
    activate:
      on-profile: master
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  redis:
    host: localhost
    port: 6379
  h2:
    console:
      enabled: false
  datasource:
    url: jdbc:mysql://localhost:3306/side-management
    username: ENC(Q9HpznBD7U06+cv77G+quQ==)
    password: ENC(vyz7S+qqJmB+hTfAaIqpHA==)
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

logging.level:
  org.hibernate.SQL: debug

jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    algorithm: PBEWithMD5AndDES
    pool-size: 2
    string-output-type: base64
    key-obtention-iterations: 100000
    password-file: C:/secret-key/secret-key.txt

logging:
  config: classpath:logback-spring.xml
