server:
  port: 8080

spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:~/side-management-h2-db
    username: ENC(H9WnDSBeO8gZJLhHEDhuig==)
    password:
    driverClassName: org.h2.Driver

  jpa:
    hibernate:
      #애플리케이션 로딩 시점에 다 드랍하고 다시 생성
      ddl-auto: create
    properties:
      hibernate:
        # show_sql: true
        format_sql: true
        use_sql_comments: true

logging.level:
  #하이버네이트가 실행하는 쿼리들이 위에 query 보기는 system.out으로 출력되고 debug는 로그로 출력
  org.hibernate.SQL: debug

jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    algorithm: PBEWithMD5AndDES
    pool-size: 2
    string-output-type: base64
    key-obtention-iterations: 100000
    password-file: C:/secret-key/secret-key.txt

logging:
  config: classpath:logback-spring.xml
